name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    # Где запускаем
    runs-on: macos-10.15
    # Что делаем
    steps:
      # Выкачиваем репозиторий
      - uses: actions/checkout@v3
      # Настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      # Запускаем тесты
      - run: ./gradlew clean test
